### ISSUE TITLE
Paper Submission 

### ISSUE THREAD

**Issue by choasma** [SiatMMLab/Awesome-Diffusion-Model-Based-Image-Editing-Methods#11]
### Paper Title

Directed Diffusion: direct control of object placement through attention guidance

### Publication

AAAI2024

### Paper Link

https://arxiv.org/abs/2302.13153

### Main Method Category

Testing-Time Finetuning

### Training-Based Specifics (Optional)

None

### Testing-Time Finetuning Specifics (Optional)

Latent Variable Optimization

### Training and Finetuning Free Specifics (Optional)

Attention Modification

### Additional Information (Optional)

This paper is published at AAAI2024 however the link is not available yet. Really appreciate all your support and the hard work of this repository. Cheers.

**Comment by liuyifan6613** [comment]
Thank you for your submission. We will add the paper to the repository list later.
Best wishes!
