### ISSUE TITLE
Paper Submission 

### ISSUE THREAD

**Issue by qqizhao** [SiatMMLab/Awesome-Diffusion-Model-Based-Image-Editing-Methods#13]
### Paper Title

Grounded-Instruct-Pix2Pix: Improving Instruction Based Image Editing with Automatic Target Grounding

### Publication

ICASSP 2024

### Paper Link

https://ieeexplore.ieee.org/document/10446377

### Main Method Category

Training and Finetuning Free

### Training-Based Specifics (Optional)

None

### Testing-Time Finetuning Specifics (Optional)

None

### Training and Finetuning Free Specifics (Optional)

Mask Guidance

**Comment by qqizhao** [comment]
Next move?

**Comment by MingfuYAN** [comment]
Thanks for your information! Your new paper has been added in this repository, and will be included in the next version of our survey paper.
