### ISSUE TITLE
Paper Submission 

### ISSUE THREAD

**Issue by hrz2000** [SiatMMLab/Awesome-Diffusion-Model-Based-Image-Editing-Methods#15]
### Paper Title

FreeEdit: Mask-free Reference-based Image Editing with Multi-modal Instruction

### Publication

arXiv 2024

### Paper Link

https://arxiv.org/abs/2409.18071

### Main Method Category

Training-Based

### Training-Based Specifics (Optional)

Instructional Editing via Full Supervision

### Testing-Time Finetuning Specifics (Optional)

None

### Training and Finetuning Free Specifics (Optional)

None

**Comment by jiaxilv** [comment]
Great work! We have uploaded your paper to our repository, and we would be happy to cite your work in our final version of the survey paper.
