### ISSUE TITLE
Paper Submission 

### ISSUE THREAD

**Issue by CostaliyA** [SiatMMLab/Awesome-Diffusion-Model-Based-Image-Editing-Methods#16]
### Paper Title

MAG-Edit: Localized Image Editing in Complex Scenarios via Mask-Based Attention-Adjusted Guidance

### Publication

ACM MM2024

### Paper Link

https://arxiv.org/abs/2312.11396

### Main Method Category

Training and Finetuning Free

### Training-Based Specifics (Optional)

None

### Testing-Time Finetuning Specifics (Optional)

None

### Training and Finetuning Free Specifics (Optional)

Attention Modification

### Additional Information (Optional)

Thank you for your great work.Our homepage is https://mag-edit.github.io/. We have released the code, welcome to communicate and star :D

**Comment by Zwette** [comment]
Thanks for your information. We have added your work.
