### ISSUE TITLE
question about imagic

### ISSUE THREAD

**Issue by Xilluill** [SiatMMLab/Awesome-Diffusion-Model-Based-Image-Editing-Methods#17]
Hi, this is a really cool survey and really helpful for me! I wonder how to evaluate imagic in your leaderboard? I did not find its open source code and demo to try it.
https://github.com/SiatMMLab/Awesome-Diffusion-Model-Based-Image-Editing-Methods/blob/5e3fa0ad5a6c52b65ff370eee90f262af26e0438/Leaderboard.md?plain=1#L27-L32

**Comment by Zwette** [comment]
Thanks for your attention! We use the implementation of diffusers (https://github.com/huggingface/diffusers/blob/main/examples/community/imagic_stable_diffusion.py) to evaluate Imagic.

**Comment by Xilluill** [comment]
Thanks to your reply! I will try it.
