### ISSUE TITLE
Paper Submission 

### ISSUE THREAD

**Issue by HolmesShuan** [SiatMMLab/Awesome-Diffusion-Model-Based-Image-Editing-Methods#18]
### Paper Title

FireFlow: Fast Inversion of Rectified Flow for Image Semantic Editing

### Publication

arXiv 2024

### Paper Link

https://arxiv.org/abs/2412.07517

### Main Method Category

Training and Finetuning Free

### Training-Based Specifics (Optional)

None

### Testing-Time Finetuning Specifics (Optional)

None

### Training and Finetuning Free Specifics (Optional)

Inversion/Sampling Modification

### Additional Information (Optional)

I am unsure if the ReFlow-based method can be included in this repository, but according to our experiments, our approach performs well and is relatively fast, thanks to the remarkable performance of the FLUX model. The code is available at https://github.com/HolmesShuan/FireFlow-Fast-Inversion-of-Rectified-Flow-for-Image-Semantic-Editing.

Thanks in advance.

**Comment by Zwette** [comment]
Thanks for your information. We have added your paper.
