### ISSUE TITLE
Add InfEdit to Inversion and Attention Modification

### ISSUE THREAD

**Issue by SihanXU** [SiatMMLab/Awesome-Diffusion-Model-Based-Image-Editing-Methods#7]
Thanks for this wonderful survey and thanks for the introduction of our CycleNet.

But we have also released [InfEdit](https://sled-group.github.io/InfEdit/) related to diffusion-based image editing last year, and it has been accepted to CVPR 2024.  Would you like to add it here please?

Thanks for your time on this survey again. I believe this will be very helpful for this area.

**Comment by MingfuYAN** [comment]
Thanks for your information! Your new paper has been added in this repository, and will be included in the next version of our survey paper.
