### ISSUE TITLE
Where is the dataset EditEval?

### ISSUE THREAD

**Issue by igodogi** [SiatMMLab/Awesome-Diffusion-Model-Based-Image-Editing-Methods#9]
![image](https://github.com/SiatMMLab/Awesome-Diffusion-Model-Based-Image-Editing-Methods/assets/26406574/4c320c08-e088-416a-9a66-3ea9731176fc)
BTW, the name of EditEval maybe conflicts with another data set.
https://github.com/facebookresearch/EditEval

**Comment by igodogi** [comment]
And codes about the benchmark?

**Comment by MingfuYAN** [comment]
@igodogi  Thanks for your information! We have uploaded the [benchmark](https://github.com/SiatMMLab/Awesome-Diffusion-Model-Based-Image-Editing-Methods/issues), and the associated code will be made public shortly.

**Comment by MingfuYAN** [comment]
> And codes about the benchmark?

The [template](https://github.com/SiatMMLab/Awesome-Diffusion-Model-Based-Image-Editing-Methods/blob/main/EditEval_v1/Metric/LMM_Score_GPT4V_Prompt_Template.md) of computing LMM Score using GPT-4V, along with a corresponding [leaderboard](https://github.com/SiatMMLab/Awesome-Diffusion-Model-Based-Image-Editing-Methods#leaderboard) comparing several leading methods, is released. Thank you for your support.
